#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

######################################################################
# Dev image...
######################################################################
FROM preset/superset:dev

COPY ./requirements/*.txt ./docker/requirements-*.txt /app/requirements/
COPY ./setup.py ./MANIFEST.in /app/

USER root
# Cache everything for dev purposes...
RUN cd /app \
    && pip install -e . \
    && pip install -r requirements/docker.txt \
    && pip install -r requirements/requirements-local.txt || true

#ODBC Driver Setup (Using Alien)

sudo apt-get install alien

RUN cd ~
RUN mkdir odbcdl
RUN  cd odbcdl/

RUN curl http://package.mapr.com/tools/MapR-ODBC/MapR_Drill/MapRDrill_odbc_v1.3.22.1055/maprdrill-1.3.22.1055-1.x86_64.rpm -o maprdrill-1.3.22.1055-1.x86_64.rpm

RUN yum localinstall -y --nogpgcheck maprdrill-1.3.22.1055-1.x86_64.rpm
RUN alien -i maprdrill-1.3.22.1055-1.x86_64.rpm

RUN cp /opt/mapr/drill/Setup/* ~
RUN mv ~/mapr.drillodbc.ini ~/.mapr.drillodbc.ini
COPY mf-odbc/odbc.ini ~/.odbc.ini
RUN mv ~/odbcinst.ini .odbcinst.ini

RUN export ODBCINI=~/.odbc.ini

RUN export MAPRDRILLINI=~/.mapr.drillodbc.ini

RUN export LD_LIBRARY_PATH=/usr/local/lib

USER superset
